
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.espark.adarsh: INFO
    org.hibernate: INFO
    com.splunk.logging.*: DEBUG

#spring.datasource.url=jdbc:h2:file:/data/demo
server:
  port: 8080

spring:
  application:
    name: springboot-splunk-hec-log4j
  config:
    activate:
      on-profile:
        - default
        - docker
        - kubernates
  splunk:
    host: localhost
    url: https://localhost:8088
    token: b01481ed-7e32-41a6-a821-4f17a59fcb92
    index: spirng_index
    source: http-log-event
    sourceType: log4j
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

