
server:
  port: 8080

spring:
  application:
    name: sprinboot-jpa
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        format-sql: true
    generate-ddl: true
    show-sql: true