
drop table IF EXISTS address;

create table address (
id bigint generated by default as identity
, country VARCHAR(255)
, state VARCHAR(255)
, street VARCHAR(255)
, primary key (id));

drop table IF EXISTS employee;

create table employee (
id bigint generated by default as identity
, career VARCHAR(255)
, first_name VARCHAR(255)
, last_name VARCHAR(255)
, address_id bigint
, primary key (id));

alter table employee add constraint FK_address_id foreign key (address_id) references address;

insert into address (id,street, state, country) values
  (10,'bang street', 'mp', 'in'),
  (20,'hyd street', 'ap', 'in'),
  (30,'ald street', 'up', 'in'),
  (40,'delhi street', 'delhi', 'in');

insert into employee (id,first_name, last_name, career,address_id) values
  (10,'adarsh', 'kumar', 'It',10),
  (20,'radha', 'singh', 'IT',20),
  (30,'sonu', 'singh', 'IT',30),
  (40,'amit', 'kumar', 'Finance',40);