
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.espark.adarsh: INFO
    org.hibernate: INFO
    com.splunk.logging.*: DEBUG

#spring.datasource.url=jdbc:h2:file:/data/demo
server:
  port: 8080

spring:
  application:
    name: springbboot-splunk
  config:
    activate:
      on-profile:
        - default
        - docker
        - kubernates
  splunk:
    host: localhost
    url: https://localhost:8088
    token: f8011a1e-92a4-43fa-801f-0bf0d65e73fb
    index: spirng_index
    source: logback
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

