spring:
  application:
    name: @spring.application.name@
  profiles:
    active: @spring.profile.active@

server:
  port: 8080
---

spring:
  application:
    name: @spring.application.name@
  profiles: rabbit
  cloud:
    stream:
      bindings:
        message-out:
          contentType: application/json
          destination: espark-topic
          group: espark-group
          producer:
            configuration:
              useNativeEncoding: true
            durableSubscription: true
            concurrency: 20
            autoStartup: true
      binder:
        rabbit:
          type: rabbit
          environment:
            spring:
              espark-rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest

---

spring:
  application:
    name: @spring.application.name@
  profiles: kafka
  cloud:
    stream:
      kafka:
        binder:
          brokers:  localhost:9092
          zkNodes:  localhost:2181
          minPartitionCount: 1
          replicationFactor: 1
          auto-create-topics: true
          auto-alter-topics: false
      bindings:
        message-out:
          contentType: application/json
          destination: espark-topic
          group: espark-group
          producer:
            configuration:
              useNativeEncoding: true
            durableSubscription: true
            concurrency: 20
            autoStartup: true
