spring:
  application:
    name: client


server:
  port: 8080


app:
  server:
    url: http://localhost:9090
    api: /server-request/


resiliency4j:
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 10s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        exponential-max-wait-duration: 90s
        retryExceptions:
          - org.springframework.web.client.HttpClientErrorException
          - org.springframework.web.client.HttpServerErrorException
    instances:
      processRequest:
        baseConfig: default

  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        minimum-number-of-calls: 3
        slow-call-rate-threshold: 50
        wait-duration-in-open-state: 20s
        automatic-translation-from-open-to-half-open-enable: true
        permitted-number-of-calls-in-half-open-state: 5
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException
          - org.springframework.web.client.HttpServerErrorException
    instances:
      processRequest:
        baseConfig: default

  ratelimiter:
    configs:
      default:
        limit-for-period: 240
        limit-refresh:-period: 60s
        timeout-duration: 10s
    instances:
      processRequest:
        baseConfig: default
