DROP TABLE SYSTEM.EMPLOYEE;
DROP SEQUENCE SYSTEM.EMPLOYEE_SEQ;

CREATE TABLE SYSTEM.Employee (
  EMP_NO INTEGER PRIMARY KEY,
  EMP_NAME VARCHAR(250) NOT NULL,
  EMP_EMAIL VARCHAR(250) NOT NULL
);

CREATE SEQUENCE SYSTEM.EMPLOYEE_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1;