CREATE OR REPLACE FUNCTION deleteEmpFunction(V_EMP_NO IN EMPLOYEE.EMP_NO%TYPE)RETURN VARCHAR
   IS
   V_EMP_DEL_MSG VARCHAR2(500);
   V_EMP_DEL_COUNT NUMBER(10) DEFAULT 0;
   V_EMP_COUNT NUMBER(10) DEFAULT 0;
   V_EMP_MSG VARCHAR2(200);
   BEGIN
      IF V_EMP_NO IS NOT NULL THEN

        SELECT COUNT(EMP.EMP_NO) INTO V_EMP_COUNT FROM EMPLOYEE EMP WHERE EMP.EMP_NO =NVL(V_EMP_NO,0);

         IF V_EMP_COUNT > 0 THEN

          SELECT EMP_NO ||' '|| EMP_NAME ||' '|| EMP_EMAIL  INTO V_EMP_MSG
             FROM EMPLOYEE WHERE EMPLOYEE.EMP_NO = NVL(V_EMP_NO,0);

          DELETE FROM EMPLOYEE WHERE EMP_NO = NVL(V_EMP_NO,0);
	          V_EMP_DEL_COUNT := SQL%ROWCOUNT;

	          IF V_EMP_DEL_COUNT >0 THEN
	             V_EMP_DEL_MSG:='EMPLOYEE DELETED SUCCESSFUL '||V_EMP_DEL_COUNT||' EMPLOYEE DELETED '||V_EMP_MSG;
	          ELSE
	             V_EMP_DEL_MSG:='EMPLOYEE NOT DELETED '||V_EMP_DEL_COUNT;
	          END IF;
	          COMMIT;

         ELSE
           V_EMP_DEL_MSG:='INVALID ARGUMENTS ID SUPPLIED TO FUNCTION';
         END IF;
	  ELSE
	      V_EMP_DEL_MSG:='IMPROPER ARGUMENTS SUPPLIED TO FUNCTION';
	  END IF;
	  RETURN (V_EMP_DEL_MSG);
   EXCEPTION
           WHEN OTHERS THEN RAISE_APPLICATION_ERROR(-20001, V_EMP_NO || ':$:' || SQLERRM, TRUE);
 END deleteEmpFunction;

//