INSERT INTO SYSTEM.Employee (EMP_NO, EMP_NAME, EMP_EMAIL) VALUES (SYSTEM.EMPLOYEE_SEQ.nextval,'adarsh', 'adarsh@kumar');
INSERT INTO SYSTEM.Employee (EMP_NO, EMP_NAME, EMP_EMAIL) VALUES (SYSTEM.EMPLOYEE_SEQ.nextval,'radha', 'radha@singh');
INSERT INTO SYSTEM.Employee (EMP_NO, EMP_NAME, EMP_EMAIL) VALUES(SYSTEM.EMPLOYEE_SEQ.nextval,'sonu', 'sonu@singh');
INSERT INTO SYSTEM.Employee (EMP_NO, EMP_NAME, EMP_EMAIL) VALUES(SYSTEM.EMPLOYEE_SEQ.nextval,'amit', 'amit@kumar');