CREATE OR REPLACE FUNCTION insertEmpFunction(
  V_EMPNO IN EMPLOYEE.EMPNO%TYPE
 ,V_EMPNAME IN EMPLOYEE.EMPNAME%TYPE
 ,V_EMPEMAIL IN EMPLOYEE.EMPEMAIL%TYPE)RETURN VARCHAR
IS
  V_EMP_INSERT_MSG VARCHAR(50);
  V_EMP_INSERT_COUNT NUMBER(10) DEFAULT 0;
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
     IF V_EMPNO IS NOT  NULL THEN

	     INSERT INTO EMPLOYEE (EMPNO,EMPNAME,EMPEMAIL)
	     VALUES(V_EMPNO,NVL(V_EMPNAME,'NOT AVAILABLE'),NVL(V_EMPEMAIL,'NOT AVAILABLE'));
	             V_EMP_INSERT_COUNT := SQL%ROWCOUNT;
	             IF V_EMP_INSERT_COUNT >0 THEN
	                 V_EMP_INSERT_MSG:='EMPLOYEE INSERT SUCCESSFUL '||V_EMP_INSERT_COUNT;
	             ELSE
	                 V_EMP_INSERT_MSG:='EMPLOYEE NOT INSERT '||V_EMP_INSERT_COUNT;
	             END IF;
	             COMMIT;
	 ELSE
	      V_EMP_INSERT_MSG:='IMPROPER ARGUMENTS SUPPLIED TO FUNCTION';
	 END IF;
     RETURN (V_EMP_INSERT_MSG);
     EXCEPTION
        WHEN OTHERS THEN RAISE_APPLICATION_ERROR (-20001, V_EMPNO ||':$:'||V_EMPNAME||':$:'||V_EMPEMAIL|| ':$:' ||SQLERRM, TRUE) ;
END insertEmpFunction;

//