CREATE OR REPLACE PROCEDURE GET_EMPLOYEE_INFO
( V_EMP_NO IN EMPLOYEE.EmpNo%TYPE, V_EMP_MSG OUT VARCHAR )
AS
BEGIN
   SELECT EmpNo ||' '|| EmpName ||' '|| EmpEmail  INTO V_EMP_MSG
   FROM EMPLOYEE WHERE EMPLOYEE.EmpNo = V_EMP_NO;
END;
//

