 CREATE TABLE Employee (
  EMP_NO INTEGER PRIMARY KEY,
  EMP_NAME VARCHAR(250) NOT NULL,
  EMP_EMAIL VARCHAR(250) NOT NULL
);

CREATE SEQUENCE EMPLOYEE_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1;


INSERT INTO Employee (EMP_NO, EMP_NAME, EMP_EMAIL) VALUES (SYSTEM.EMPLOYEE_SEQ.nextval,'adarsh', 'adarsh@kumar');
INSERT INTO Employee (EMP_NO, EMP_NAME, EMP_EMAIL) VALUES (SYSTEM.EMPLOYEE_SEQ.nextval,'radha', 'radha@singh');
INSERT INTO Employee (EMP_NO, EMP_NAME, EMP_EMAIL) VALUES(SYSTEM.EMPLOYEE_SEQ.nextval,'sonu', 'sonu@singh');
INSERT INTO Employee (EMP_NO, EMP_NAME, EMP_EMAIL) VALUES(SYSTEM.EMPLOYEE_SEQ.nextval,'amit', 'amit@kumar');



CREATE OR REPLACE FUNCTION updateEmpFunction(
  V_EMPNO IN EMPLOYEE.EMP_NO%TYPE
 ,V_EMPNAME IN EMPLOYEE.EMP_NAME%TYPE
 ,V_EMPEMAIL IN EMPLOYEE.EMP_EMAIL%TYPE)RETURN VARCHAR
IS
    V_EMP__UPDATE_MSG VARCHAR2(500);
    V_EMP_UPDATE_COUNT NUMBER(10) DEFAULT 0;
    V_EMP_MSG VARCHAR2(200);
BEGIN
      IF V_EMPNO IS NOT NULL THEN
	      UPDATE EMPLOYEE SET EMP_NAME=V_EMPNAME, EMP_EMAIL=V_EMPEMAIL WHERE EMP_NO=NVL(V_EMPNO,0);
	            V_EMP_UPDATE_COUNT := SQL%ROWCOUNT;
	            IF V_EMP_UPDATE_COUNT >0 THEN
	               SELECT EMP_NO ||' '|| EMP_NAME ||' '|| EMP_EMAIL  INTO V_EMP_MSG
                          FROM EMPLOYEE WHERE EMPLOYEE.EMP_NO = V_EMPNO;
	               V_EMP__UPDATE_MSG:='EMPLOYEE UPDATED SUCCESSFUL '||V_EMP_UPDATE_COUNT || 'UPDATED EMPLOYEE DATA' ||V_EMP_MSG;
	            ELSE
	               V_EMP__UPDATE_MSG:='EMPLOYEE NOT UPDATED '||V_EMP_UPDATE_COUNT;
	            END IF;
	            COMMIT;
	  ELSE
	      V_EMP__UPDATE_MSG:='IMPROPER ARGUMENTS SUPPLIED TO FUNCTION';
	  END IF;
	RETURN (V_EMP__UPDATE_MSG);
	EXCEPTION
	      WHEN OTHERS THEN RAISE_APPLICATION_ERROR (-20001, V_EMPNO    || ':$:' || SQLERRM, TRUE);
COMMIT;
END updateEmpFunction;

//