CREATE OR REPLACE FUNCTION updateEmpFunction(
  V_EMPNO IN EMPLOYEE.EMP_NO%TYPE
 ,V_EMPNAME IN EMPLOYEE.EMP_NAME%TYPE
 ,V_EMPEMAIL IN EMPLOYEE.EMP_EMAIL%TYPE)RETURN VARCHAR
IS
    V_EMP__UPDATE_MSG VARCHAR2(500);
    V_EMP_UPDATE_COUNT NUMBER(10) DEFAULT 0;
    V_EMP_MSG VARCHAR2(200);
BEGIN
      IF V_EMPNO IS NOT NULL THEN
	      UPDATE EMPLOYEE SET EMP_NAME=V_EMPNAME, EMP_EMAIL=V_EMPEMAIL WHERE EMP_NO=NVL(V_EMPNO,0);
	            V_EMP_UPDATE_COUNT := SQL%ROWCOUNT;
	            IF V_EMP_UPDATE_COUNT >0 THEN
	               SELECT EMP_NO ||' '|| EMP_NAME ||' '|| EMP_EMAIL  INTO V_EMP_MSG
                          FROM EMPLOYEE WHERE EMPLOYEE.EMP_NO = V_EMPNO;
	               V_EMP__UPDATE_MSG:='EMPLOYEE UPDATED SUCCESSFUL '||V_EMP_UPDATE_COUNT || 'UPDATED EMPLOYEE DATA' ||V_EMP_MSG;
	            ELSE
	               V_EMP__UPDATE_MSG:='EMPLOYEE NOT UPDATED '||V_EMP_UPDATE_COUNT;
	            END IF;
	            COMMIT;
	  ELSE
	      V_EMP__UPDATE_MSG:='IMPROPER ARGUMENTS SUPPLIED TO FUNCTION';
	  END IF;
	RETURN (V_EMP__UPDATE_MSG);
	EXCEPTION
	      WHEN OTHERS THEN RAISE_APPLICATION_ERROR (-20001, V_EMPNO    || ':$:' || SQLERRM, TRUE);
COMMIT;
END updateEmpFunction;

//