CREATE OR REPLACE FUNCTION updateEmpFunction(
  V_EMPNO IN EMPLOYEE.EMPNO%TYPE
 ,V_EMPNAME IN EMPLOYEE.EMPNAME%TYPE
 ,V_EMPEMAIL IN EMPLOYEE.EMPEMAIL%TYPE)RETURN VARCHAR
IS
    V_EMP__UPDATE_MSG VARCHAR(50);
    V_EMP_UPDATE_COUNT NUMBER(10) DEFAULT 0;
BEGIN
      IF V_EMPNO IS NOT NULL THEN
	      UPDATE EMPLOYEE SET EMPNAME=V_EMPNAME, EMPEMAIL=V_EMPEMAIL WHERE EMPNO=NVL(V_EMPNO,0);
	            V_EMP_UPDATE_COUNT := SQL%ROWCOUNT;
	            IF V_EMP_UPDATE_COUNT >0 THEN
	               V_EMP__UPDATE_MSG:='EMPLOYEE UPDATED SUCCESSFUL '||V_EMP_UPDATE_COUNT;
	            ELSE
	               V_EMP__UPDATE_MSG:='EMPLOYEE NOT UPDATED '||V_EMP_UPDATE_COUNT;
	            END IF;
	            COMMIT;
	  ELSE
	      V_EMP__UPDATE_MSG:='IMPROPER ARGUMENTS SUPPLIED TO FUNCTION';
	  END IF;
	RETURN (V_EMP__UPDATE_MSG);
	EXCEPTION
	      WHEN OTHERS THEN RAISE_APPLICATION_ERROR (-20001, V_EMPNO    || ':$:' || SQLERRM, TRUE);
COMMIT;
END updateEmpFunction;

//