version: "3.1"

services:

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - spring-ms

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_CREATE_TOPICS=espark-topic
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - spring-ms
    depends_on:
      - zookeeper

  kafka-producer:
    image: adarshkumarsingh83/kafka-producer
    restart: on-failure:5
    volumes:
      - /data/kafka-producer
    ports:
      - 8080:8080
    links:
      - kafka
      - zookeeper
    depends_on:
      - kafka
      - zookeeper
    environment:
      - SPRING_PROFILES_ACTIVE=kafka-container
      - KAFKA_DESTINATION=espark-topic
      - KAFKA_GROUP=espark-group
      - KAFKA_BORKER=kafka:9092
      - ZOOKEEPER_NODE=zookeeper:2181
    networks:
      - spring-ms

  kafka-processor:
    image: adarshkumarsingh83/kafka-processor
    restart: on-failure:5
    volumes:
      - /data/kafka-processor
    ports:
      - 8899:8899
    links:
      - kafka
      - zookeeper
    depends_on:
      - kafka
      - zookeeper
    environment:
      - SPRING_PROFILES_ACTIVE=kafka-container
      - KAFKA_SOURCE=espark-topic
      - KAFKA_DESTINATION=espark-topic-processed
      - KAFKA_GROUP=espark-group
      - KAFKA_BORKER=kafka:9092
      - ZOOKEEPER_NODE=zookeeper:2181
    networks:
      - spring-ms

  kafka-consumer:
    image: adarshkumarsingh83/kafka-consumer
    restart: on-failure:5
    volumes:
      - /data/kafka-consumer
    ports:
      - 9090:9090
    links:
      - kafka
      - zookeeper
    depends_on:
      - kafka
      - zookeeper
    environment:
      - SPRING_PROFILES_ACTIVE=kafka-container
      - KAFKA_DESTINATION=espark-topic-processed
      - KAFKA_GROUP=espark-group
      - KAFKA_BORKER=kafka:9092
      - ZOOKEEPER_NODE=zookeeper:2181
    networks:
      - spring-ms

networks:
  spring-ms: