server:
  port: 8080

logging:
  level:
    root: DEBUG
  com:
    espark:
      adarsh: INFO

espark:
  swagger:
    directories:
      -
        directory: swagger-apis
        fileName: swagger.yaml
        locations:
          - api1
          - api2

spring:
  application:
    name: springboot-swagager-yml
