CREATE OR REPLACE PROCEDURE deleteEmpProcedure(V_EMP_NO IN EMPLOYEE.EMPNO%TYPE,V_EMP_DEL_MSG OUT VARCHAR)
   IS
     V_EMP_DEL_COUNT NUMBER(10) DEFAULT 0;
   BEGIN
      DELETE FROM EMPLOYEE WHERE EMPNO = V_EMP_NO;
	         V_EMP_DEL_COUNT := SQL%ROWCOUNT;
	  IF V_EMP_DEL_COUNT >0 THEN
	     V_EMP_DEL_MSG:='EMPLOYEE DELETED SUCCESSFUL '||V_EMP_DEL_COUNT;
	  ELSE
	     V_EMP_DEL_MSG:='EMPLOYEE NOT DELETED '||V_EMP_DEL_COUNT;
	  END IF;
	  COMMIT;

	  EXCEPTION
	     WHEN OTHERS THEN RAISE_APPLICATION_ERROR(-20001, V_EMP_NO || ':$:' || SQLERRM, TRUE);
   END deleteEmpProcedure;

//