CREATE OR REPLACE PROCEDURE getAllEmpProcedure(EMP_ALL_DATA_CURSOR OUT SYS_REFCURSOR,V_SELECT_ERROR_MSG OUT VARCHAR)
IS
BEGIN
  OPEN EMP_ALL_DATA_CURSOR FOR

   SELECT EMP.EMPNO,EMP.EMPNAME,EMP.EMPEMAIL FROM EMPLOYEE EMP;

       IF EMP_ALL_DATA_CURSOR%NOTFOUND THEN
	      V_SELECT_ERROR_MSG :='NO EMPLOYEE FOUND ';
	   END IF;

 EXCEPTION
      WHEN NO_DATA_FOUND THEN
          BEGIN
            V_SELECT_ERROR_MSG:='NO EMPLOYEE FOUND';
          END;
      WHEN OTHERS THEN
	      RAISE_APPLICATION_ERROR (-20001, 'EXCEPTION GENERATED :$:' || SQLERRM, TRUE) ;
END getAllEmpProcedure;

//