CREATE OR REPLACE PROCEDURE getEmpProcedure(
V_EMP_NO IN EMPLOYEE.EMP_NO%TYPE
,EMP_DATA_CURSOR OUT SYS_REFCURSOR,
V_SELECT_ERROR_MSG OUT VARCHAR)
IS
BEGIN
    OPEN EMP_DATA_CURSOR FOR
    SELECT EMP.EMP_NO,EMP.EMP_NAME,EMP.EMP_EMAIL FROM EMPLOYEE EMP WHERE EMP.EMP_NO = V_EMP_NO;
	
	 IF EMP_DATA_CURSOR%NOTFOUND THEN
	      V_SELECT_ERROR_MSG :='NO EMPLOYEE FOUND FOR EMP_NO '||V_EMP_NO;
	 END IF;  
	
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
          BEGIN
            RAISE_APPLICATION_ERROR(-20610,'NO EMPLOYEE FOUND');
          END;
        WHEN TOO_MANY_ROWS THEN
          BEGIN
            RAISE_APPLICATION_ERROR(-20612,'MORE THEN ONE EMPLOYEE FOUND FOR EMP_NO '||V_EMP_NO);
          END;
        WHEN OTHERS THEN
		    RAISE_APPLICATION_ERROR(-20001, V_EMP_NO || ':$:' || SQLERRM, TRUE) ;
END getEmpProcedure;

//