CREATE OR REPLACE PROCEDURE insertEmpProcedure(
  V_EMPNO IN EMPLOYEE.EMPNO%TYPE
 ,V_EMPNAME IN EMPLOYEE.EMPNAME%TYPE
 ,V_EMPEMAIL IN EMPLOYEE.EMPEMAIL%TYPE
 ,V_EMP_INSERT_MSG OUT VARCHAR)
IS
  V_EMP_INSERT_COUNT NUMBER(10) DEFAULT 0;
BEGIN
	INSERT INTO EMPLOYEE (EMPNO,EMPNAME,EMPEMAIL) VALUES(V_EMPNO,V_EMPNAME,V_EMPEMAIL);
		   V_EMP_INSERT_COUNT := SQL%ROWCOUNT;

	   IF V_EMP_INSERT_COUNT >0 THEN
	       V_EMP_INSERT_MSG:='EMPLOYEE INSERT SUCCESSFUL '||V_EMP_INSERT_COUNT;
	   ELSE
	       V_EMP_INSERT_MSG:='EMPLOYEE NOT INSERT '||V_EMP_INSERT_COUNT;
	  END IF;
	  COMMIT;

  EXCEPTION
        WHEN OTHERS THEN RAISE_APPLICATION_ERROR (-20001, V_EMPNO ||':$:'||V_EMPNAME||':$:'||V_EMPEMAIL|| ':$:' ||SQLERRM, TRUE) ;
END insertEmpProcedure;

//