CREATE OR REPLACE PROCEDURE updateEmpProcedure(
  V_EMPNO IN EMPLOYEE.EMPNO%TYPE
 ,V_EMPNAME IN EMPLOYEE.EMPNAME%TYPE
 ,V_EMPEMAIL IN EMPLOYEE.EMPEMAIL%TYPE
 ,V_EMP_UPDATE_MSG OUT VARCHAR)
IS
    V_EMP_UPDATE_COUNT NUMBER(10) DEFAULT 0;
BEGIN
	 UPDATE EMPLOYEE SET EMPNAME=V_EMPNAME, EMPEMAIL=V_EMPEMAIL WHERE EMPNO=V_EMPNO;
	 V_EMP_UPDATE_COUNT := SQL%ROWCOUNT;
	   IF V_EMP_UPDATE_COUNT >0 THEN
	     V_EMP_UPDATE_MSG:='EMPLOYEE UPDATED SUCCESSFUL '||V_EMP_UPDATE_COUNT;
	   ELSE
	     V_EMP_UPDATE_MSG:='EMPLOYEE NOT UPDATED '||V_EMP_UPDATE_COUNT;
	  END IF;
	COMMIT;
	EXCEPTION
	      WHEN OTHERS THEN RAISE_APPLICATION_ERROR (-20001, V_EMPNO    || ':$:' || SQLERRM, TRUE);
COMMIT;
END updateEmpProcedure;

//