
spring:
  application:
    name: springboot-custom-healthcheck-actuator

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'