FROM openjdk:8
MAINTAINER adarsh.kumar@gmail.com
COPY target/springbboot-openapi-security.jar springbboot-openapi-security.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","springbboot-openapi-security.jar"]