kind: Service
apiVersion: v1
metadata:
  name: springboot-elasticsearch
spec:
  selector:
    app: springboot-elasticsearch
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-elasticsearch
spec:
  selector:
    matchLabels:
      app: springboot-elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-elasticsearch
    spec:
      containers:
        - name: springboot-elasticsearch
          image: "adarshkumarsingh83/springboot-elasticsearch"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:   # Setting environmental Variables
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: ELASTIC_NODES
              value: elasticsearch:9300
            - name: ELASTIC_NAME
              value: elasticsearch
            - name: ELASTIC_INDEX
              value: epsark-index
          volumeMounts:
            - name: springboot-elasticsearch
              mountPath: /var/logs
      volumes:
        - name: springboot-elasticsearch
          emptyDir: {}