FROM openjdk:17-oracle
MAINTAINER adarsh.kumar@gmail.com
COPY target/springboot3-prometheus-grafana.jar springboot3-prometheus-grafana.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","springboot3-prometheus-grafana.jar"]