server:
  port: 9090

spring:
  application:
    name: springboot-neo4j-docker
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: secret


---

spring:
  application:
    name: springboot-neo4j-docker
  profiles:
    - docker
  data:
    neo4j:
      uri: bolt://neo4j:7687
      username: neo4j
      password: secret