spring:
  application:
    name: springboot-ssl-client
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0
  output:
    ansi:
      enabled: DETECT


server:
  port: 9090
  key-store: classpath:espark.p12
  key-store-password: esparkpwd
  serviceHost: http://localhost:8443
  protocall: TLSv1.2
  serviceUrl:
    info: /actuator/info
    beans: /actuator/beans
    health: /actuator/health
    metrics: /actuator/metrics

logging:
  level:
    root: DEBUG
    com.espark.adarsh: DEBUG
    org.springframework.web: DEBUG
    group:
      com.espark.adarsh: DEBUG
      org.springframework.web: DEBUG
  file:
    name: /var/logs/application.log
    max-size: 1MB
    max-history: 10
  pattern:
    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.zip

