logging:
  level:
    root: INFO

spring:
  application:
    name: spring-streams-processor-kafka
  cloud:
    stream:
      function:
        definition: processor
      bindings:
        processor-in-0:
          destination: dataChannelTopic
        processor-out-0:
          destination: dataChannelTopicProcessor
      kafka:
        binder:
          brokers: localhost:9092