
drop table IF EXISTS department;

create table department (
id bigint generated by default as identity
, name VARCHAR(255)
, country VARCHAR(255)
, state VARCHAR(255)
, street VARCHAR(255)
, primary key (id));

drop table IF EXISTS employee;

create table employee (
id bigint generated by default as identity
, career VARCHAR(255)
, first_name VARCHAR(255)
, last_name VARCHAR(255)
, department_id bigint
, primary key (id));

alter table employee add constraint FK_department_id foreign key (department_id) references department;

insert into department (id,name,street, state, country) values
  (10,'it','bang street', 'mp', 'in'),
  (20,'it','hyd street', 'ap', 'in'),
  (30,'it','ald street', 'up', 'in'),
  (40,'fa','delhi street', 'delhi', 'in');

insert into employee (id,first_name, last_name, career,department_id) values
  (10,'adarsh', 'kumar', 'It',10),
  (20,'radha', 'singh', 'IT',20),
  (30,'sonu', 'singh', 'IT',30),
  (40,'amit', 'kumar', 'Finance',40);