version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=espark
      - MYSQL_USER=espark-root
      - MYSQL_PASSWORD=espark-root
    ports:
      - 3306:3306
    volumes:
      - /data/espark-mysql