version: '3.7'
services:
  neo4j:
    container_name: neo4j
    image: neo4j:4.0.3
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/secret
      NEO4J_dbms_logs_debug_level: DEBUG
#    networks:
#      - spring-ms

#  springboot-neo4j-docker:
#    container_name: springboot-neo4j-docker
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    restart: on-failure:5
#    ports:
#      - 9090:9090
#    links:
#      - neo4j
#    depends_on:
#      - neo4j
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring-ms
#networks:
#  spring-ms: